### PR TITLE
Fix wallet and addresses balance and link buttons in wallet Pages to actions in the backend

### LINKED ISSUE #108: Balance of wallets and addresses is wrong, and actions in qml are not linked with the backend
**Describe the bug**
In wallets page the balance of wallets is not shown and the balance of addresses is in the wrong format and the buttons an actions related with wallets page are not linked with the backend

### PR DESCRIPTION
**Pull request by mauricio1802**
Fixes #108 

Changes:
- Change use of harcoded strings to use const variables
- Convert coins properly 
- Change QML Code for validation and generation of seeds
- Links button of wallets page to methods in backend
Does this change need to mentioned in CHANGELOG.md?
no

### CODE REVIEW

**Comment by olemis** [comment]
@stdevMac @stdevMauricio1802 merge conflicts

File: src/coin/skycoin/models/account.go [hunk 1]
```diff
@@ -43,8 +43,11 @@ func (addr SkycoinAddress) ListPendingTransactions() core.TransactionIterator {
 
 func (wlt RemoteWallet) GetBalance(ticker string) (uint64, error) {
 	c := wlt.newClient()
+
 	bl, err := c.WalletBalance(wlt.Id)
+
 	if err != nil {
+
```
Comment (olemis) [inline src/coin/skycoin/models/account.go]: unnecessary newline whitespace

File: src/coin/skycoin/models/wallet.go [hunk 2]
```diff
@@ -98,9 +98,12 @@ func (wltSrv *SkycoinRemoteWallet) CreateWallet(label string, seed string, IsEnc
 		c := wltSrv.newClient()
 		wltR, err := c.CreateWallet(wltOpt)
 		if err != nil {
+
```
Comment (olemis) [inline src/coin/skycoin/models/wallet.go]: unnecessary whitespce

File: src/coin/skycoin/models/wallet.go [hunk 3]
```diff
@@ -98,9 +98,12 @@ func (wltSrv *SkycoinRemoteWallet) CreateWallet(label string, seed string, IsEnc
...
 			return nil, err
+
```
Comment (olemis) [inline src/coin/skycoin/models/wallet.go]: unnecessary whitespce

File: src/coin/skycoin/models/wallet.go [hunk 4]
```diff
@@ -380,21 +384,34 @@ func (wltSrv *SkycoinLocalWallet) GetWallet(id string) core.Wallet {
...
+	} else {
+		wlt, err = wallet.NewWallet(wltName, opts)
+		if err != nil {
+
+			return nil, err
+		}
 	}
+
 	if err := wallet.Save(wlt, wltSrv.walletDir); err != nil {
+
```
Comment (olemis) [inline src/coin/skycoin/models/wallet.go]: unnecessary whitespce

File: src/ui/Delegates/WalletListAddressDelegate.qml [hunk 5]
```diff
@@ -68,16 +69,45 @@ Item {
...
             Material.foreground: Material.Grey
             Layout.fillWidth: true
 
-            onCheckedChanged: {
-                encryptionEnabled = checked
+            onCheckedChanged:{
+                checked = encryptionEnabled
+                text = checked ? "Decrypt wallet" : "Encrypt wallet"
+            }
+            //Connections{
```
Comment (olemis) [inline src/ui/Delegates/WalletListAddressDelegate.qml:84]: Why this code commented out ? Remove ?

File: src/ui/PageWallets.qml [hunk 6]
```diff
@@ -142,7 +125,14 @@ Page {
 
         onAccepted: {
             console.log("Add wallet")
-            listWallets.append( { "name": name, "encryptionEnabled": encryptionEnabled, "sky": 0, "coinHours": 0 } )
+            //if (encryptionEnabled){
```
Comment (olemis) [inline src/ui/PageWallets.qml]: Why this code commented out ? Remove ?

File: src/ui/main.qml [hunk 7]
```diff
@@ -176,6 +176,8 @@ ApplicationWindow {
         modal: true
     }
 
+
```
Comment (olemis) [inline src/ui/main.qml:186]: unnecessary whitespce

**Review by olemis — CHANGES_REQUESTED** [review]

**Comment by olemis** [comment]
@stdevMauricio1802 merge conflicts ...

**Comment by olemis** [comment]
@stdevMauricio1802 conflicts
